server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/psy
  #    username: user
  #    password: 1234
  profiles:
    include:
      - database
    active : local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
